### ISSUE TITLE
MacOS BigSur Installer as VHDX Issue

### ISSUE THREAD

**Issue by excelsi** [Qonfused/OSX-Hyper-V#17]
I converted a MacOSBigSur DMG to VHDX as described with qemu-img and attached the VHDX to the VM but then i got this error:

![image](https://github.com/user-attachments/assets/32d2ef6d-8211-4934-bc8b-65426cb521a0)

This is my VM Config:

![image](https://github.com/user-attachments/assets/ebbe91d7-80ad-47eb-9808-ac67dfdc6384)

and these are my BigSur Files:

![image](https://github.com/user-attachments/assets/ef75d870-8356-4057-876f-efa675bcdd84)

The DMG was generated after this Guide:
https://iboysoft.com/de/nachricht/macos-big-sur-dmg-herunterladen.html

**Comment by Qonfused** [comment]
The DMG created with `hdiutil` appears to be a valid target for `qemu-img` to convert -- I would try converting it back to a DMG and see if you can still mount/open it. I hadn't tested this method above Mac OS Sierra and I'm not sure if you can convert the newer **InstallAssistant.pkg** image formats this way.

However, as an alternative, you can also [manually create the VHDX disk](https://github.com/Qonfused/OSX-Hyper-V?tab=readme-ov-file#i-create-a-boot-vhdx-disk) and [download the BaseSystem image](https://github.com/Qonfused/OSX-Hyper-V?tab=readme-ov-file#ii-create-a-macos-installerrecovery-vhdx-disk) for BigSur.

If you built the project locally (i.e. with `.\scripts\build.ps1`), you can also run the `create-macos-recovery.ps1` and `convert-efi-disk.ps1` scripts from the created **dist\Scripts** directory. As mentioned in the README, the `create-virtual-machine.ps1` script will also do these steps for you and also configure the virtual machine.

**Comment by excelsi** [comment]
I used now the Phyton Script to download the BasSystem Recovery Image and installed BigSur this way
