### ISSUE TITLE
Booting Sequoia on AMD Ryzen 9 7900X3D

### ISSUE THREAD

**Issue by Mukul1127** [Qonfused/OSX-Hyper-V#19]
Hello, I have been trying for a while to get Sequoia booting in Hyper-V, here are my steps:

1. Clone [OSX-Hyper-V](https://github.com/Qonfused/OSX-Hyper-V) and [ProperTree](https://github.com/corpnewt/ProperTree)
2. Edit config.yml to include [extra AMD patches](https://github.com/Qonfused/OSX-Hyper-V/issues/5)
3. Use ProperTree to add the [rest of the AMD patches](https://github.com/AMD-OSX/AMD_Vanilla/blob/master/patches.plist) and [set core count](https://dortania.github.io/OpenCore-Install-Guide/AMD/zen.html#patch-2)
4. Create VM using powershell script
5. Try and run it in Hyper-V Manager

Output: It just restarts seconds after typing 1. Same this as here: https://github.com/Qonfused/OSX-Hyper-V/issues/12#issuecomment-2213498727

https://github.com/user-attachments/assets/00d6c267-a549-4178-a3fe-a65edc1de7bd

**Comment by Mukul1127** [comment]
I also tried fixing critial issues in https://sanitychecker.ocutils.me/ expect WhateverGreen

**Comment by Qonfused** [comment]
Is this with [`DummyPowerManagement`](https://github.com/Qonfused/OCE-Build/blob/main/docs/schema.md#kernel---emulate---dummypowermanagement) enabled? From what I recall in #12, they tried additional booter quirks in https://github.com/Qonfused/OSX-Hyper-V/issues/12#issuecomment-2223541598 which shouldn't be necessary. Unfortunately I haven't been able to reproduce their issue on the 3950X.

**Comment by Mukul1127** [comment]
Yes it is

**Comment by Qonfused** [comment]
I see. What you've done already should be all that you need to do for that CPU. I can't see the video uploaded but I figure as this is happening so quickly after the boot picker that this is probably propping up during the initial [boot.efi handoff](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/boot.html#boot-efi-handoff).

Just to see how it's being detected, could you upload your OpenCore log? It gets created on your EFI partition (next to your EFI folder), either from a DEBUG build or from enabling these options:
https://github.com/Qonfused/OSX-Hyper-V/blob/31fd2fe6dcf131435a17375dc8dd7aa61eeb8407/src/config.yml#L80-L101

![image](https://github.com/user-attachments/assets/e8899b42-5db8-4328-ae70-85f9bc08bb92)

Enabling those debug options should prevent an immediate reboot and show a kernel panic, which will help narrow down the issue.

**Comment by Mukul1127** [comment]
OK

**Comment by Mukul1127** [comment]
Are they supposed to be readable, Notepad++ shows a bunch of gibberish
[opencore-2024-09-22-161311.txt](https://github.com/user-attachments/files/17091147/opencore-2024-09-22-161311.txt)
[opencore-2024-09-22-161321.txt](https://github.com/user-attachments/files/17091148/opencore-2024-09-22-161321.txt)

Also here's the video on mediafire: https://www.mediafire.com/file/lkzuvglo2cxw7fg/Compressed_Desktop_2024.09.22_-_12.45.03.02.mp4/file

**Comment by Mukul1127** [comment]
NVM using NanaZip broke it, mounted it using explorer instead:
[opencore-2024-09-22-161321.txt](https://github.com/user-attachments/files/17091213/opencore-2024-09-22-161321.txt)
[opencore-2024-09-22-161311.txt](https://github.com/user-attachments/files/17091214/opencore-2024-09-22-161311.txt)

**Comment by Qonfused** [comment]
I've noticed that some of your patches under [`ACPI > Patch`](https://github.com/Qonfused/OCE-Build/blob/main/docs/schema.md#acpi---patch) and [`Kernel > Patch`](https://github.com/Qonfused/OCE-Build/blob/main/docs/schema.md#kernel---patch) are missing some schema entries (or are probably mislocated):
![Screenshot 2024-09-22 at 3 37 34 PM](https://github.com/user-attachments/assets/4e3a3ff6-819c-4e92-b63c-56fdf1cc2ff9)

Unfortunately this output (same as what ocvalidate would output) doesn't show the full plist path to tell where these entries are.

Patches from the config.yml file should have the correct schema filled automatically, though any additional patches you've added to your config.plist (after build) will only contain fields you've added (e.g. 'find' and 'replace' fields).

I can try and find where these are if you upload your config.plist, though I'd start by verifying that your ACPI and Kernel patches are located under `ACPI > Patch` and `Kernel > Patch` in your config.plist (in case they were accidentally dragged in ProperTree).

**Comment by Mukul1127** [comment]
Here's the plist: 
[config.plist.txt](https://github.com/user-attachments/files/17091302/config.plist.txt)

**Comment by Qonfused** [comment]
Ah I see. You've added your AMD kernel patches under the `ACPI > Patch` entries.
![image](https://github.com/user-attachments/assets/993032e4-7e57-4338-bb8e-220020346c74)

I've moved them back under the `Kernel > Patch` section:
[config.plist.zip](https://github.com/user-attachments/files/17091321/config.plist.zip)

**Comment by Mukul1127** [comment]
oh, sorry, I just fixed it myself

**Comment by Mukul1127** [comment]
No change, here's the new logs:
[opencore-2024-09-22-171748.txt](https://github.com/user-attachments/files/17091330/opencore-2024-09-22-171748.txt)
[opencore-2024-09-22-171736.txt](https://github.com/user-attachments/files/17091331/opencore-2024-09-22-171736.txt)
[opencore-2024-09-22-171744.txt](https://github.com/user-attachments/files/17091332/opencore-2024-09-22-171744.txt)

**Comment by Mukul1127** [comment]
Also if it helps, here's my current setup:
[dist.zip](https://github.com/user-attachments/files/17091353/dist.zip)

**Comment by Qonfused** [comment]
I don't see any more issues in your OpenCore log (during boot.efi handoff), but anything that happens now after booting into the installer ([XNU/kernel handoff](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/boot.html#xnu-kernel-handoff)) won't show up in the OpenCore log.

Does your VM display a kernel panic on screen or does it still immediately reboot? You can also enable [serial debugging](https://dortania.github.io/OpenCore-Install-Guide/troubleshooting/kernel-debugging.html#config-plist-setup) to stream the same output (as was also done in https://github.com/Qonfused/OSX-Hyper-V/issues/12#issuecomment-2213498727).

**Comment by Mukul1127** [comment]
I don't think it showed a kernel panic, I'll try serial

**Comment by Mukul1127** [comment]
What I got from com1:

#[EB|LOG:EXITBS:END] _
#[EB.BST.FBS|-]
#[EB|B:BOOT]
#[EB|LOG:HANDOFF TO XNU] _
======== End of efiboot serial output. ========

**Comment by Qonfused** [comment]
You'll need to enable [`Misc > Serial > Init`](https://github.com/Qonfused/OCE-Build/blob/main/docs/schema.md#misc---serial---init) and add the `serial=3` boot arg to capture logs from XNU. Even if the system immediately reboots, it should capture any panics in the serial output.

**Comment by Mukul1127** [comment]
OK

**Comment by Mukul1127** [comment]
How can I set boot args

**Comment by Mukul1127** [comment]
nvm I figured it out

**Comment by Mukul1127** [comment]
No change in Serial Output:

#[EB|LOG:EXITBS:END] _
#[EB.BST.FBS|-]
#[EB|B:BOOT]
#[EB|LOG:HANDOFF TO XNU] _
======== End of efiboot serial output. ========

**Comment by Mukul1127** [comment]
Closing this as I have managed to get linux installed and I will just use qemu.
