### ISSUE TITLE
can't open file 'U:\\OSX-Hyper-V\\scripts\\Utilities\\macrecovery\\macrecovery.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by startergo** [Qonfused/OSX-Hyper-V#22]
```
PowerShell 7.4.6
PS C:\Windows\System32> cd "U:\OSX-Hyper-V"
PS U:\OSX-Hyper-V> .\scripts\lib\create-virtual-machine.ps1 -name "Sequoia"
C:\Program Files\Python313\python.exe: can't open file 'U:\\OSX-Hyper-V\\scripts\\Utilities\\macrecovery\\macrecovery.py': [Errno 2] No such file or directory
```
![image](https://github.com/user-attachments/assets/0313da12-1f11-45ae-a902-bb63f389149d)

**Comment by startergo** [comment]
The build/download instructions are very confusing. Maybe the readme file needs to be rewritten.

**Comment by startergo** [comment]
After 
```
scripts\build.ps1
```
It should be:
```
.\dist\Scripts\create-virtual-machine.ps1 -name "Sequoia"
```

**Comment by Qonfused** [comment]
Yeah, you need to build the project first and run the scripts from the build directory. Those scripts under `scripts/lib` aren't meant to be run from there; they get moved to a `dist/Scripts` directory besides the `dist/Utilities` directory.

> The build/download instructions are very confusing. Maybe the readme file needs to be rewritten.

I agree. I wrote it as a WIKI just to provide the information, but it loses clarify doing that so it can be confusing to follow linearly.
