### ISSUE TITLE
Installer GUI fails to start

### ISSUE THREAD

**Issue by startergo** [Qonfused/OSX-Hyper-V#23]
![image](https://github.com/user-attachments/assets/49e6105e-191b-40f2-8b3a-afba8d23ae65)
Is this a normal process?
It is scrolling the same for an hour.

**Comment by startergo** [comment]
Rebooted and came up with the same error.

**Comment by Qonfused** [comment]
Same issue as in #20. Apparently more common than I thought.

**Comment by startergo** [comment]
From what I can see it is AMD specific and I have Intel x299 CPU.

**Comment by Qonfused** [comment]
That issue tracks the same issue on Intel, while #13 is (or was) AMD-specific.

**Comment by startergo** [comment]
```
19:279 00:002 OC: Prelinked injection skips MacHyperVSupport.kext () kext at 1 due to version 0 <= 240100 <= 200909
19:283 00:004 OCAK: Patching invalid size 2000 with 1B44000 for com.apple.iokit.IOACPIFamily
```

**Comment by Qonfused** [comment]
> > That issue tracks the same issue on Intel
> 
> But he installed 3 kexts which don't make any sense for fixing the issue.

In his case it was likely a flaky issue. I don't believe any changes they made were functional or relevant for the issue. In any case it's the same behavior, so it's easier to track this in a single issue.

> ```
> 19:279 00:002 OC: Prelinked injection skips MacHyperVSupport.kext () kext at 1 due to version 0 <= 240100 <= 200909
> ```

The base MacHyperVSupport kext isn't loaded above Big Sur; OpenCore is reporting that the kernel version is above the 20.9.9 threshold set so it's skipping loading it.

https://github.com/Qonfused/OSX-Hyper-V/blob/e051c1afdfeca97f97415b6ed9cd9dc0123da6f2/src/build.yml#L21-L30

**Comment by startergo** [comment]
But the script is supposed to download the latest macOS. Why is it downloading Monterey? There is a kext for 21.0.0 and above.

**Comment by Qonfused** [comment]
The kernel version reported is 24.01.00 which is Sequoia so you aren't booting itno Monterey. There is a separate MacHyperVSupport kext for Monterey and above (MacHyperVSupportMonterey), but it isn't limited to just Monterey.

**Comment by startergo** [comment]
![image](https://github.com/user-attachments/assets/e7e411a3-ba30-4624-b027-c9428fccc621)
This is in the config in the EFI folder. It it only the config or the whole folder is for less than Monterey?

**Comment by startergo** [comment]
`build.ps1` is supposed to download the latest EFI folder correct?

**Comment by startergo** [comment]
The config should be like this:
![image](https://github.com/user-attachments/assets/5545bfc9-3149-4778-911e-ca5042e84791)

**Comment by startergo** [comment]
![image](https://github.com/user-attachments/assets/ee36ec76-b62e-46d7-bade-6b3020453ff3)

**Comment by startergo** [comment]
Ao this so this not work then?
https://github.com/Qonfused/OSX-Hyper-V/blob/main/src/build.yml#L21-L25

**Comment by Qonfused** [comment]
Seems like a regression with the nightly build of OCE-Build. The kext is still present under the kexts folder but you'll have to manually add a new entry for it in your config.plist under `Kernel > Add`:
![image](https://github.com/user-attachments/assets/63a4e0f2-f35e-4688-bddb-ec08cb3e74c4)

**Comment by startergo** [comment]
Shouldn't [this](https://github.com/Qonfused/OSX-Hyper-V/blob/main/src/build.yml#L23) be `specifier: latest`?

**Comment by Qonfused** [comment]
The wildcard specifier essentially defers extraction to whatever gets downloaded as part of the build; we're relying on the fact that it is bundled with the MacHyperVSupport release.

The current issue is that the two kexts have the same cfbundle identifier so one of the two gets picked arbitrarily and deletes the other entry. I've just fixed this in https://github.com/Qonfused/OCE-Build/commit/6876435a54a3a96a95d3af0b1035fef8c9b5a7ad and will trigger a re-build to update it here.
