### ISSUE TITLE
The AMD 5950X starts macOS and gets stuck here.

### ISSUE THREAD

**Issue by ssdsl0126** [Qonfused/OSX-Hyper-V#27]
![image](https://github.com/user-attachments/assets/2ea3a081-7999-41d4-b90d-6b3d3eec59d7)
[opencore-2024-11-18-212055.txt](https://github.com/user-attachments/files/17800782/opencore-2024-11-18-212055.txt)
config.plist：[config.plist.txt](https://github.com/user-attachments/files/17800786/config.plist.txt)

**Comment by Qonfused** [comment]
You're missing the rest of the [AMD kernel patches](https://github.com/AMD-OSX/AMD_Vanilla):
![image](https://github.com/user-attachments/assets/713f1401-373d-4510-b96f-d4870a7186ca)

**Comment by ssdsl0126** [comment]
[opencore-2024-11-19-080815.txt](https://github.com/user-attachments/files/17807518/opencore-2024-11-19-080815.txt)
config.plist：[config.plist.txt](https://github.com/user-attachments/files/17807524/config.plist.txt)
Copy the entire AMD kernel patches

**Comment by ssdsl0126** [comment]
https://github.com/Qonfused/OSX-Hyper-V/issues/24#issuecomment-2463859043
