### ISSUE TITLE
DDA GPU passthrough cannot be recognise.

### ISSUE THREAD

**Issue by krpr** [Qonfused/OSX-Hyper-V#33]
macOS cannot recognise the GPU passthrough by DDA.
seems like Hyper-V Gen2 VMs use some special PCIE emulation(or something else), Lilu.kext or WhateverGreen.kext cannot discover those passthroug device.
Is there any solution to passthrough GPU to macOS vm?
Thanks

**Comment by Qonfused** [comment]
It's mentioned in the [limitations section](https://github.com/Qonfused/OSX-Hyper-V?tab=readme-ov-file#limitations) of the README that patching w/ Lilu and WhateverGreen is blocked by https://github.com/acidanthera/bugtracker/issues/2299 as the PCI bridges exposed by MacHyperVSupport are detected too late to patch with Lilu. Somewhat related is https://github.com/Qonfused/OSX-Hyper-V/issues/6#issuecomment-2037277344.
