### ISSUE TITLE
How to enable audio support?

### ISSUE THREAD

**Issue by luomo-pro** [Qonfused/OSX-Hyper-V#9]
Hello, I am using Hyper-V to install macOS 14.
Now I find that the sound in macOS cannot be played through the Windows speakers.
Is there any way to hear the sound in macOS?
Thank you!

**Comment by Qonfused** [comment]
Hyper-V unfortunately does not provide audio virtualization. As mentioned in the README, no audio device is given to the VM by default:

https://github.com/Qonfused/OSX-Hyper-V/blob/b16b38a3533386bbba4c083d84344334839c05fa/docs/README.md?plain=1#L499-L500

One of the options that might be apparent if you have access to a Windows edition with DDA support is to pass in a supported GPU, though there are issues with detecting devices early enough to apply patches w/ AppleALC and WhateverGreen (refer to the README; also explained in #6).

The best option at the moment is to use a virtual audio device that can behave as an audio sink/loopback device. You can the open-source [Blackhole](https://github.com/ExistentialAudio/BlackHole) driver to capture desktop audio and route it through a network-enabled app between macOS and the Windows host (I've done this with OBS Ninja in the past or through a networked USB-interface with [VirtualHere](https://www.virtualhere.com/)).
